#!/bin/sh

# Use neovim for vim if present.
[ -x "$(command -v nvim)" ] && alias vim="nvim" vimdiff="nvim -d"

# Use $XINITRC variable if file exists.
[ -f "$XINITRC" ] && alias startx="startx $XINITRC"

# sudo not required for some system commands
for command in mount umount sv pacman updatedb su shutdown poweroff reboot ; do
	alias $command="sudo $command"
done; unset command

# Verbosity and settings that you pretty much just always are going to want.
alias \
	cp="cp -iv" \
	mv="mv -iv" \
	rm="rm -vI" \
	bc="bc -ql" \
	mkd="mkdir -pv" \
	yt="youtube-dl --add-metadata -i" \
	yta="yt -x5 -f bestaudio/best" \
	ffmpeg="ffmpeg -hide_banner"

# Colorize commands when possible.
alias \
	ls="ls -hN --color=auto --group-directories-first" \
	grep="grep --color=auto" \
	diff="diff --color=auto" \
	ccat="highlight --out-format=ansi"

# easier to read disk
alias \
	df="df -h" \
	free="free -m"

alias \
	la="ls -a --color=auto --group-directories-first" \
	ll="ls -alhF --color=auto" \
	lsd="ls -lahF --color=auto | grep --color=never '^d'" \

alias \
	xclip="xclip -sel clip" \
	reload="exec ${SHELL} -l" \

alias config-home="/usr/bin/git --git-dir=$HOME/.cfg/ --work-tree=$HOME" \

alias yarn='yarn --use-yarnrc "$XDG_CONFIG_HOME/yarn/config"'
alias nvidia-settings='nvidia-settings --config="$XDG_CONFIG_HOME/nvidia/settings"'
alias wget=wget --hsts-file="$XDG_DATA_HOME/wget-hsts"

alias hst="cat ~/.cache/zsh/history | fzf | xclip"
